[package]
name = "world_id_root_registry_starknet"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.16.1"

[dev-dependencies]
snforge_std = "0.57.0"
assert_macros = "2.16.1"

[scripts]
deploy = "bash deploy.sh"
test = "snforge test"

[[target.starknet-contract]]
sierra = true

[tool.snforge]
