[toolchain]
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
world_id_root_registry_solana = "2xuveg4Aeuhhhy67DMTRfJfQE5MK7iPF2F4gCAFGM7N7"

[programs.localnet]
world_id_root_registry_solana = "HpgNxwdekXixEW6ZzTPsjhhFx46fpfoC7ruJvsinPYHx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./wallet.json"

[scripts]
test = "npm run test:anchor"
